// Combined mock movie dataset (trimmed for brevity; you can expand later)
export const mockMovies = [
  { id: 1, title: "Thunivu", year: 2023, rating: 7.5, genre: "Tamil/Action/Heist", poster: "https://placehold.co/250x375/5a5a5a/ffffff?text=Thunivu", summary: "A mysterious mastermind and his team take over a bank to expose financial corruption.", director: "H. Vinoth", cast: "Ajith Kumar, Manju Warrier, Samuthirakani" },
  { id: 2, title: "Valimai", year: 2022, rating: 6.0, genre: "Tamil/Action/Thriller", poster: "https://placehold.co/250x375/5a5a5a/ffffff?text=Valimai", summary: "A police officer hunts a gang of notorious motorcycle racers.", director: "H. Vinoth", cast: "Ajith Kumar, Huma Qureshi" },
  { id: 3, title: "Nerkonda Paarvai", year: 2019, rating: 8.0, genre: "Tamil/Drama/Courtroom", poster: "https://placehold.co/250x375/5a5a5a/ffffff?text=Nerkonda", summary: "A retired lawyer takes up the case of three young women.", director: "H. Vinoth", cast: "Ajith Kumar, Shraddha Srinath" },
  { id: 4, title: "Viswasam", year: 2019, rating: 7.3, genre: "Tamil/Action/Family", poster: "https://placehold.co/250x375/5a5a5a/ffffff?text=Viswasam", summary: "A village chieftain reunites with his wife and daughter.", director: "Siva", cast: "Ajith Kumar, Nayanthara" },
  { id: 5, title: "Vivegam", year: 2017, rating: 6.2, genre: "Tamil/Action/Spy", poster: "https://placehold.co/250x375/5a5a5a/ffffff?text=Vivegam", summary: "An Interpol agent is betrayed and must fight back.", director: "Siva", cast: "Ajith Kumar, Kajal Aggarwal" },
  { id: 6, title: "Inception", year: 2010, rating: 8.8, genre: "Action/Sci-Fi", poster: "https://placehold.co/250x375/f43f5e/ffffff?text=Inception", summary: "A thief who steals corporate secrets through dream-sharing technology.", director: "Christopher Nolan", cast: "Leonardo DiCaprio" },
  { id: 7, title: "Interstellar", year: 2014, rating: 8.6, genre: "Sci-Fi/Adventure", poster: "https://placehold.co/250x375/fb923c/ffffff?text=Interstellar", summary: "Explorers travel through a wormhole to ensure humanity's survival.", director: "Christopher Nolan", cast: "Matthew McConaughey" },
  { id: 8, title: "The Dark Knight", year: 2008, rating: 9.0, genre: "Action/Crime", poster: "https://placehold.co/250x375/8b5cf6/ffffff?text=Dark+Knight", summary: "The Joker wreaks havoc on Gotham.", director: "Christopher Nolan", cast: "Christian Bale, Heath Ledger" },
  { id: 9, title: "Pulp Fiction", year: 1994, rating: 8.9, genre: "Crime/Drama", poster: "https://placehold.co/250x375/84cc16/ffffff?text=Pulp+Fiction", summary: "Intertwined tales of violence and redemption.", director: "Quentin Tarantino", cast: "John Travolta" },
  { id: 10, title: "Oppenheimer", year: 2023, rating: 8.6, genre: "Biography/Drama", poster: "https://placehold.co/250x375/ef4444/ffffff?text=Oppenheimer", summary: "The story of J. Robert Oppenheimer and the Manhattan Project.", director: "Christopher Nolan", cast: "Cillian Murphy" }
];
